version: '3'
services:
  gpt-researcher:
    image: kramer1346/gptresearcher
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 8000:8000
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app