name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:






      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py


name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py

name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gptresearcher/gpt-researcher:latest
          file: Dockerfile
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio gpt-researcher
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/all-6-report-types.py

